application: devteambuzz
version: 2
runtime: python
api_version: 1

handlers:
- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: teambuzz.py
